CREATE TABLE USERS(
Id int IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name NVARCHAR(MAX) NULL,
EmailId NVARCHAR(200) NULL,
Mobile NVARCHAR(20) NULL,
Address NVARCHAR(MAX),
IsActive BIT
)

ALTER TABLE USERS
ALTER COLUMN IsActive BIT NOT NULL;

INSERT INTO USERS(Name, EmailId, Mobile, Address, IsActive) VALUES ('Abhishek','abhishelligikar@gmail.com','8456789420','Ram Mandir Gulbarga',0)
INSERT INTO USERS VALUES ('Aditya','adi123kulkarni@gmail.com','2354678910','Ram Mandir Gulbarga',0)

SELECT * FROM USERS

CREATE PROCEDURE SaveUsers  
(    
@Name NVARCHAR(MAX),  
@EmailId NVARCHAR(MAX),  
@Mobile NVARCHAR(20),  
@Address NVARCHAR(MAX),  
@IsActive BIT  
)  
AS  
BEGIN  
   SET NOCOUNT ON;
   BEGIN TRY
		SET @IsActive = 0
		INSERT INTO USERS VALUES (@Name,@EmailId,@Mobile,@Address,@IsActive)
   END TRY

   BEGIN CATCH
		DECLARE @ERRORSTATE INT,
				@ERRORSEVERITY INT,
				@ERRORMESSAGE NVARCHAR(MAX)
		SELECT @ERRORSTATE = ERROR_STATE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   END CATCH

END  

EXEC SaveUsers 'Anjana','anjanakulkarni@gmail.com','3654789201','Ram Mandir Gulbarga',0
EXEC SaveUsers 'fdsfsdf','sdfdf@gmail.com','3213213332','Ram Gulbarga',0


CREATE PROCEDURE GetUsers 
AS  
BEGIN  
    SET NOCOUNT ON; 
	BEGIN TRY
    SELECT * FROM Users(NOLOCK) ORDER BY Id ASC  
	END TRY

	BEGIN CATCH
		DECLARE @ERRORSTATE INT,
				@ERRORSEVERITY INT,
				@ERRORMESSAGE NVARCHAR(MAX)
		SELECT @ERRORSTATE = ERROR_STATE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   END CATCH
END 

EXEC GetUsers


CREATE PROCEDURE DeleteUser  
( 
@Id INT
)  
AS  
BEGIN  
    SET NOCOUNT ON; 
	BEGIN TRY
    IF EXISTS (SELECT 1 FROM Users WHERE Id = @Id)  
    BEGIN  
        DELETE FROM Users WHERE Id = @Id;
    END
	END TRY
	BEGIN CATCH
		DECLARE @ERRORSTATE INT,
				@ERRORSEVERITY INT,
				@ERRORMESSAGE NVARCHAR(MAX)
		SELECT @ERRORSTATE = ERROR_STATE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   END CATCH
END 

EXEC DeleteUser 3;


CREATE PROCEDURE UpdateUsers  
( 
@Id INT,
@Name NVARCHAR(MAX),  
@EmailId NVARCHAR(MAX),  
@Mobile NVARCHAR(20),  
@Address NVARCHAR(MAX),  
@IsActive BIT  
)  
AS  
BEGIN  
   SET NOCOUNT ON;
   BEGIN TRY
   IF EXISTS (SELECT Id FROM Users WHERE Id = @Id)
		UPDATE USERS
		SET Name = @Name,
			EmailId = @EmailId,
			Mobile = @Mobile,
			Address = @Address,
			IsActive = @IsActive
		WHERE Id = @Id
   END TRY

   BEGIN CATCH
		DECLARE @ERRORSTATE INT,
				@ERRORSEVERITY INT,
				@ERRORMESSAGE NVARCHAR(MAX)
		SELECT @ERRORSTATE = ERROR_STATE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   END CATCH

END

EXEC UpdateUsers 8,'SATISH A K','satishshelligikar@gmail.com','4567829870','Ram Mandir Gulbarga',0