CREATE TABLE USERS(
Id int IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name NVARCHAR(MAX) NULL,
EmailId NVARCHAR(200) NULL,
Mobile NVARCHAR(20) NULL,
Address NVARCHAR(MAX),
IsActive BIT NOT NULL
)

ALTER TABLE USERS
ALTER COLUMN IsActive BIT NOT NULL;

INSERT INTO USERS(Name, EmailId, Mobile, Address, IsActive) VALUES ('Abhishek','abhishelligikar@gmail.com','8456789420','Ram Mandir Gulbarga',0)
INSERT INTO USERS VALUES ('Aditya','adi123kulkarni@gmail.com','2354678910','Ram Mandir Gulbarga',0)

SELECT * FROM USERS

CREATE PROCEDURE SaveUser  
(    
@Name NVARCHAR(MAX),  
@EmailId NVARCHAR(MAX),  
@Mobile NVARCHAR(20),  
@Address NVARCHAR(MAX),  
@IsActive BIT,
@ReturnCode NVARCHAR(20) OUTPUT  
)  
AS  
BEGIN  
   SET NOCOUNT ON;
   BEGIN TRY
		IF EXISTS (SELECT 1 FROM USERS WHERE Mobile = @Mobile)
		BEGIN
			SET @ReturnCode = 'C202'
			RETURN
		END
		IF EXISTS (SELECT 1 FROM USERS WHERE EmailId = @EmailId)
		BEGIN
			SET @ReturnCode = 'C201'  
            RETURN 
		END
		ELSE
		BEGIN
			INSERT INTO Users (Name,EmailId,Mobile,Address,IsActive) VALUES (@Name,@EmailId,@Mobile,@Address,1)  
			SET @ReturnCode = 'C200'  
		END
   END TRY

   BEGIN CATCH
		DECLARE @ERRORSTATE INT,
				@ERRORSEVERITY INT,
				@ERRORMESSAGE NVARCHAR(MAX)
		SELECT @ERRORSTATE = ERROR_STATE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   END CATCH

END 

EXEC SaveUsers 'Anjana','anjanakulkarni@gmail.com','3654789201','Ram Mandir Gulbarga',0,'cs200'
EXEC SaveUsers 'fdsfsdf','sdfdf@gmail.com','3213213332','Ram Gulbarga',0,'cs201'


CREATE PROCEDURE GetUsers 
AS  
BEGIN  
    SET NOCOUNT ON; 
	BEGIN TRY
    SELECT * FROM Users(NOLOCK) ORDER BY Id ASC  
	END TRY

	BEGIN CATCH
		DECLARE @ERRORSTATE INT,
				@ERRORSEVERITY INT,
				@ERRORMESSAGE NVARCHAR(MAX)
		SELECT @ERRORSTATE = ERROR_STATE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   END CATCH
END 

EXEC GetUsers


CREATE PROCEDURE DeleteUser  
( 
@Id INT,
@ReturnCode NVARCHAR(20) OUTPUT 
)  
AS  
BEGIN  
    SET NOCOUNT ON;  
    SET @ReturnCode = 'C200'
	BEGIN TRY
    IF NOT EXISTS (SELECT 1 FROM Users WHERE Id = @Id)  
    BEGIN  
        SET @ReturnCode ='C203'  
        RETURN
    END
	ELSE
	BEGIN
		DELETE FROM Users WHERE Id = @Id  
        	SET @ReturnCode = 'C200'  
        	RETURN
	END
	END TRY
	BEGIN CATCH
		DECLARE @ERRORSTATE INT,
			@ERRORSEVERITY INT,
			@ERRORMESSAGE NVARCHAR(MAX)
		SELECT  @ERRORSTATE = ERROR_STATE(),
			@ERRORSEVERITY = ERROR_SEVERITY(),
			@ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   	END CATCH
END

EXEC DeleteUser 8,'cs201'


CREATE PROCEDURE UpdateUsers  
( 
@Id INT,
@Name NVARCHAR(MAX),  
@EmailId NVARCHAR(MAX),  
@Mobile NVARCHAR(20),  
@Address NVARCHAR(MAX),  
@IsActive BIT,
@ReturnCode NVARCHAR(20) OUTPUT 
)  
AS  
BEGIN  
   SET NOCOUNT ON;
   BEGIN TRY
   IF EXISTS (SELECT Id FROM Users WHERE Id = @Id)
		UPDATE USERS
		SET Name = @Name,
			EmailId = @EmailId,
			Mobile = @Mobile,
			Address = @Address,
			IsActive = @IsActive
		WHERE Id = @Id
		SET @ReturnCode = 'C200'
		RETURN
   END TRY

   BEGIN CATCH
		DECLARE @ERRORSTATE INT,
				@ERRORSEVERITY INT,
				@ERRORMESSAGE NVARCHAR(MAX)
		SELECT @ERRORSTATE = ERROR_STATE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORMESSAGE = ERROR_MESSAGE()
		RAISERROR(@ERRORSTATE,@ERRORSEVERITY,@ERRORMESSAGE)
   END CATCH

END

EXEC UpdateUsers 8,'SATISH KULKARNI','satishshelligikar@gmail.com','1234567890','RAM MANDIR GULBARGA',0,'cs201'
